"""Added articles, saved_articles, user_preferences, user_countries_preferences

Revision ID: e0935e2fd3f8
Revises: 426e0b6a488a
Create Date: 2025-09-22 17:18:51.376117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0935e2fd3f8'
down_revision: Union[str, Sequence[str], None] = '426e0b6a488a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.Enum('BUSINESS', 'ENTERTAINMENT', 'GENERAL', 'HEALTH', 'SCIENCE', 'SPORTS', 'TECHNOLOGY', 'POLITICS', 'TRAVEL', name='categoryenum'), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_articles_category'), 'articles', ['category'], unique=False)
    op.create_index(op.f('ix_articles_country'), 'articles', ['country'], unique=False)
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_table('saved_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'article_id', name='uq_user_article')
    )
    op.create_index(op.f('ix_saved_articles_article_id'), 'saved_articles', ['article_id'], unique=False)
    op.create_index(op.f('ix_saved_articles_id'), 'saved_articles', ['id'], unique=False)
    op.create_index(op.f('ix_saved_articles_user_id'), 'saved_articles', ['user_id'], unique=False)
    op.create_table('user_country_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'country_code', name='uq_user_country')
    )
    op.create_index(op.f('ix_user_country_preferences_id'), 'user_country_preferences', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('BUSINESS', 'ENTERTAINMENT', 'GENERAL', 'HEALTH', 'SCIENCE', 'SPORTS', 'TECHNOLOGY', 'POLITICS', 'TRAVEL', name='categoryenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_user_category')
    )
    op.create_index(op.f('ix_user_preferences_category'), 'user_preferences', ['category'], unique=False)
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_category'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_country_preferences_id'), table_name='user_country_preferences')
    op.drop_table('user_country_preferences')
    op.drop_index(op.f('ix_saved_articles_user_id'), table_name='saved_articles')
    op.drop_index(op.f('ix_saved_articles_id'), table_name='saved_articles')
    op.drop_index(op.f('ix_saved_articles_article_id'), table_name='saved_articles')
    op.drop_table('saved_articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_country'), table_name='articles')
    op.drop_index(op.f('ix_articles_category'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
